---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - dev
      - staging
      - prod
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n-service-monitor
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: n8n
  namespaceSelector:
    matchNames:
      - dev
      - staging
      - prod
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
