---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-hello-world-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: dev
          - name: staging
            namespace: staging
          - name: prod
            namespace: prod

  template:
    metadata:
      name: hos-argocd-{{name}}
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true # delete if a resource was deleted
          selfHeal: false
          allowEmpty: false # don't allow empty resources
        syncOptions:
        - CreateNamespace=true
        - Validate=true # don't apply if doesn't validated
        - PrunePropagationPolicy=foreground # safety measure to delete EVERYTHING
        - PruneLast=true # delete as the last option, after every change/add is done
      source:
        repoURL: https://github.com/IliaDiv/hos-argocd.git
        targetRevision: test
        path: kubernetes/Home-Office-Store
        helm:
          valueFiles:
            - ../../environment/{{namespace}}/eks/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
