##############################################################################################
# ALB Controller
##############################################################################################

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress/kubernetes.io/certificate-arn: {{ .Values.ingress.certARN }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.rules.host }}
    http:
      paths:
      - path: {{ .Values.ingress.rules.frontendPaths.path }}
        pathType: {{ .Values.ingress.rules.frontendPaths.pathType }}
        backend:
          service:
            name: {{ .Values.frontend.service.name }}
            port:
              number: {{ .Values.frontend.service.ports.port}}
      - path: {{ .Values.ingress.rules.backendPaths.path }}
        pathType: {{ .Values.ingress.rules.backendPaths.pathType }}
        backend:
          service:
            name: {{ .Values.backend.service.name }}
            port:
              number: {{ .Values.backend.service.ports.port }}
      - path: {{ .Values.ingress.rules.n8nPaths.path }}
        pathType: {{ .Values.ingress.rules.n8nPaths.pathType }}
        backend:
          service:
            name: {{ .Values.n8n.service.name }}
            port:
              number: {{ .Values.n8n.service.ports.port }}
