##############################################################################################
# Secrets
##############################################################################################
{{- if and .Values.ingress.enabled (eq .Values.ingress.type "traefik") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
stringData:
  db_user: {{ .Values.secrets.data.db_user }}
  db_password: {{ .Values.secrets.data.db_password }}
  n8n_api_key: {{ .Values.secrets.data.n8n_api_key }}
  n8n_encryption_key: {{ .Values.secrets.data.n8n_encryption_key }}
  open_ai_api_key: {{ .Values.secrets.data.open_ai_api_key }}
{{- end }}