---
##############################################################################################
# Backend Service
##############################################################################################

{{- if and .Values.ingress.enabled (eq .Values.ingress.type "traefik") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    app: backend
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.backend.service.ports.port }}
    protocol: {{ .Values.backend.service.ports.protocol }}
    targetPort: {{ .Values.backend.service.ports.targetPort }}
  selector:
    app: backend
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
  type: {{ .Values.backend.service.type }}
{{- end }}

---
##############################################################################################
# Frontend Service
##############################################################################################

{{- if and .Values.ingress.enabled (eq .Values.ingress.type "traefik") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    app: frontend
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.frontend.service.ports.port }}
    protocol: {{ .Values.frontend.service.ports.protocol }}
    targetPort: {{ .Values.frontend.service.ports.targetPort }}
  selector:
    app: frontend
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
  type: {{ .Values.frontend.service.type }}
{{- end }}

---
##############################################################################################
# N8N Service
##############################################################################################

{{- if and .Values.ingress.enabled (eq .Values.ingress.type "traefik") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.n8n.service.name }}
  labels:
    app: n8n
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.n8n.service.ports.port }}
    protocol: {{ .Values.n8n.service.ports.protocol }}
    targetPort: {{ .Values.n8n.service.ports.targetPort }}
  selector:
    app: n8n
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
  type: {{ .Values.n8n.service.type }}
{{- end }}

---
##############################################################################################
# PostgreSQL Service
##############################################################################################

#{{- if and .Values.ingress.enabled (eq .Values.ingress.type "traefik") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
  labels:
    db: postgresql
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.postgresql.service.clusterIP }}
  clusterIPs:
  - {{ .Values.postgresql.service.clusterIPs }}
  selector:
    db: postgresql
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
  type: {{ .Values.postgresql.service.type }}
{{- end }}
---
