---
##############################################################################################
# PostgreSQL StatefulSet
##############################################################################################
#{{- if and .Values.ingress.enabled (eq .Values.ingress.type "traefik") }}
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ .Values.postgresql.name }}
  labels:
    db: postgresql
    {{- include "Home-Office-Store.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.postgresql.service.name }}
  selector:
    matchLabels:
      db: postgresql
      {{- include "Home-Office-Store.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        db: postgresql
        {{- include "Home-Office-Store.labels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgresql.postgresql.image }}
        ports:
        - containerPort: {{ .Values.postgresql.postgresql.port }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.cm.name }}
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: db_password
        {{- include "Home-Office-Store.postgresql.resources" . | nindent 8 }}
#{{- end }}
